version: '2'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: sendy_co
      MYSQL_USER: sendy
      MYSQL_PASSWORD: sendy

    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
  sendy:
    image: smartbrood/nginx-php-fpm
    ports:
      - "80:80"
    volumes:
      - /tmp/sendy:/data/htdocs/sendy
      - ./files/sendy.conf:/etc/nginx/conf.d/default.conf
    links:
      - mysql:mysql

volumes:
  mysql_volume:
